version: '3.9'

services:
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
      - ./data:/app/data
      - static:/backend_static
      - media:/app/media
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    depends_on:
      - backend
    build: ./infra/
    env_file: .env
    ports:
      - 8080:80 
    volumes:
      - static:/static/
      - media:/media
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

volumes:
  static:
  media:
  data: